FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["src/Product.Api/Product.Api.csproj", "src/Product.Api/"]
COPY ["src/ProductDomain/ProductDomain.csproj", "src/ProductDomain/"]
RUN dotnet restore -s "https://vmnugets.azurewebsites.net/nuget" -s "https://api.nuget.org/v3/index.json" "src/Product.Api/Product.Api.csproj"
COPY . .
WORKDIR "/src/src/Product.Api"
RUN dotnet build "Product.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Product.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Product.Api.dll"]